2019-10-04 10:43:13 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%9D%92%E6%B5%B7%E7%9C%81&page=18>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.135.24.11:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 10:43:26 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%9D%92%E6%B5%B7%E7%9C%81&page=1>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.8:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 10:59:54 [py.warnings] WARNING: D:\Miniconda3\lib\site-packages\pymysql\cursors.py:329: Warning: (1265, "Data truncated for column 'title' at row 1")
  self._do_get_result()

2019-10-04 11:05:30 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%8C%97%E4%BA%AC%E5%B8%82&page=2>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.194:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:13:09 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%8C%97%E4%BA%AC%E5%B8%82&page=4>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E5%8C%97%E4%BA%AC%E5%B8%82&page=4 took longer than 30.0 seconds..
2019-10-04 11:18:12 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%8C%97%E4%BA%AC%E5%B8%82&page=12>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.184:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:18:49 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%8C%97%E4%BA%AC%E5%B8%82&page=20>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.107.98:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:19:00 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%8C%97%E4%BA%AC%E5%B8%82&page=21>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 106.52.181.184:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:19:44 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%8C%97%E4%BA%AC%E5%B8%82&page=14>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 124.161.160.251:8085 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:19:55 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%8C%97%E4%BA%AC%E5%B8%82&page=30>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 120.77.45.130:80 [{'status': 500, 'reason': b'Internal Server Error'}]
2019-10-04 11:20:03 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%A4%A9%E6%B4%A5%E5%B8%82&page=3>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.194:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:20:11 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%8C%97%E4%BA%AC%E5%B8%82&page=22>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.187:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:21:35 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%8C%97%E4%BA%AC%E5%B8%82&page=29>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.TCPTimedOutError: TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2019-10-04 11:21:35 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%A4%A9%E6%B4%A5%E5%B8%82&page=7>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.TCPTimedOutError: TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2019-10-04 11:21:35 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%A4%A9%E6%B4%A5%E5%B8%82&page=9>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.224:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:21:41 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%A4%A9%E6%B4%A5%E5%B8%82&page=10>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.10:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:22:35 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%A4%A9%E6%B4%A5%E5%B8%82&page=21>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.9:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:22:42 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%A4%A9%E6%B4%A5%E5%B8%82&page=29>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2019-10-04 11:23:17 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E4%B8%8A%E6%B5%B7%E5%B8%82&page=4>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E4%B8%8A%E6%B5%B7%E5%B8%82&page=4 took longer than 30.0 seconds..
2019-10-04 11:23:28 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E4%B8%8A%E6%B5%B7%E5%B8%82&page=6>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.224:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:24:15 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E4%B8%8A%E6%B5%B7%E5%B8%82&page=12>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.9:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:24:30 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E4%B8%8A%E6%B5%B7%E5%B8%82&page=16>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 120.77.45.130:80 [{'status': 500, 'reason': b'Internal Server Error'}]
2019-10-04 11:24:46 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E4%B8%8A%E6%B5%B7%E5%B8%82&page=19>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2019-10-04 11:24:55 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E4%B8%8A%E6%B5%B7%E5%B8%82&page=24>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 120.77.45.130:80 [{'status': 500, 'reason': b'Internal Server Error'}]
2019-10-04 11:25:30 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E4%B8%8A%E6%B5%B7%E5%B8%82&page=26>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.185:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:25:59 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E4%B8%8A%E6%B5%B7%E5%B8%82&page=22>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.9:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:43:02 [py.warnings] WARNING: D:\Miniconda3\lib\site-packages\pymysql\cursors.py:329: Warning: (1265, "Data truncated for column 'title' at row 1")
  self._do_get_result()

2019-10-04 11:44:59 [py.warnings] WARNING: D:\Miniconda3\lib\site-packages\pymysql\cursors.py:329: Warning: (1265, "Data truncated for column 'title' at row 1")
  self._do_get_result()

2019-10-04 11:49:51 [py.warnings] WARNING: D:\Miniconda3\lib\site-packages\pymysql\cursors.py:329: Warning: (1265, "Data truncated for column 'title' at row 1")
  self._do_get_result()

2019-10-04 11:52:49 [py.warnings] WARNING: D:\Miniconda3\lib\site-packages\pymysql\cursors.py:329: Warning: (1265, "Data truncated for column 'title' at row 1")
  self._do_get_result()

2019-10-04 11:53:22 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%8C%97%E4%BA%AC%E5%B8%82&page=12>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.226:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:53:23 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%8C%97%E4%BA%AC%E5%B8%82&page=10>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.TCPTimedOutError: TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2019-10-04 11:57:29 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%A4%A9%E6%B4%A5%E5%B8%82&page=17>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.TCPTimedOutError: TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2019-10-04 11:57:57 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%8C%97%E4%BA%AC%E5%B8%82&page=10>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.184:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:58:02 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%A4%A9%E6%B4%A5%E5%B8%82&page=17>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 120.77.45.130:80 [{'status': 500, 'reason': b'Internal Server Error'}]
2019-10-04 11:58:17 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%A4%A9%E6%B4%A5%E5%B8%82&page=25>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E5%A4%A9%E6%B4%A5%E5%B8%82&page=25 took longer than 30.0 seconds..
2019-10-04 12:00:54 [py.warnings] WARNING: D:\Miniconda3\lib\site-packages\pymysql\cursors.py:329: Warning: (1265, "Data truncated for column 'title' at row 1")
  self._do_get_result()

2019-10-04 12:01:57 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E4%B8%8A%E6%B5%B7%E5%B8%82&page=22>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.226:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:03:44 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E4%B8%8A%E6%B5%B7%E5%B8%82&page=22>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 27.159.166.62:9999 [{'status': 503, 'reason': b'Service Unavailable'}]
2019-10-04 12:04:13 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%87%8D%E5%BA%86%E5%B8%82&page=23>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.8:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:06:32 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%87%8D%E5%BA%86%E5%B8%82&page=23>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.186:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:07:24 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B2%B3%E5%8C%97%E7%9C%81&page=16>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.225:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:08:20 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%A4%A9%E6%B4%A5%E5%B8%82&page=17>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.221:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:10:18 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%87%8D%E5%BA%86%E5%B8%82&page=23>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E9%87%8D%E5%BA%86%E5%B8%82&page=23 took longer than 30.0 seconds..
2019-10-04 12:11:01 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B2%B3%E5%8C%97%E7%9C%81&page=28>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.222:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:11:25 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B2%B3%E5%8C%97%E7%9C%81&page=8>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.TCPTimedOutError: TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2019-10-04 12:13:10 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B1%B1%E8%A5%BF%E7%9C%81&page=22>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.190:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:13:49 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B1%B1%E8%A5%BF%E7%9C%81&page=29>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.10:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:13:50 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E8%BE%BD%E5%AE%81%E7%9C%81&page=1>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E8%BE%BD%E5%AE%81%E7%9C%81&page=1 took longer than 30.0 seconds..
2019-10-04 12:14:36 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E8%BE%BD%E5%AE%81%E7%9C%81&page=7>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.9:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:17:38 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B2%B3%E5%8C%97%E7%9C%81&page=28>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 124.161.160.251:8085 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:20:02 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B1%B1%E8%A5%BF%E7%9C%81&page=22>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 117.191.11.107:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:21:43 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B1%B1%E8%A5%BF%E7%9C%81&page=29>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.223:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:24:51 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B1%B1%E8%A5%BF%E7%9C%81&page=22>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.189:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:25:03 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%BB%91%E9%BE%99%E6%B1%9F%E7%9C%81&page=13>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.184:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:25:35 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%BB%91%E9%BE%99%E6%B1%9F%E7%9C%81&page=22>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.223:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:25:38 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B1%B1%E8%A5%BF%E7%9C%81&page=22>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.8:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:26:02 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%BB%91%E9%BE%99%E6%B1%9F%E7%9C%81&page=29>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.195:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:26:24 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%BB%91%E9%BE%99%E6%B1%9F%E7%9C%81&page=16>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E9%BB%91%E9%BE%99%E6%B1%9F%E7%9C%81&page=16 took longer than 30.0 seconds..
2019-10-04 12:26:31 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%BB%91%E9%BE%99%E6%B1%9F%E7%9C%81&page=30>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E9%BB%91%E9%BE%99%E6%B1%9F%E7%9C%81&page=30 took longer than 30.0 seconds..
2019-10-04 12:31:13 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B1%9F%E8%8B%8F%E7%9C%81&page=23>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.221:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:33:19 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%99%E6%B1%9F%E7%9C%81&page=1>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%99%E6%B1%9F%E7%9C%81&page=1 took longer than 30.0 seconds..
2019-10-04 12:35:46 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%99%E6%B1%9F%E7%9C%81&page=23>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%99%E6%B1%9F%E7%9C%81&page=23 took longer than 30.0 seconds..
2019-10-04 12:36:33 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B1%9F%E8%8B%8F%E7%9C%81&page=8>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.184:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:37:13 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B1%9F%E8%8B%8F%E7%9C%81&page=9>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.10:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:38:20 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B1%9F%E8%8B%8F%E7%9C%81&page=10>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E6%B1%9F%E8%8B%8F%E7%9C%81&page=10 took longer than 30.0 seconds..
2019-10-04 12:39:41 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%BB%91%E9%BE%99%E6%B1%9F%E7%9C%81&page=30>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E9%BB%91%E9%BE%99%E6%B1%9F%E7%9C%81&page=30 took longer than 30.0 seconds..
2019-10-04 12:39:55 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B1%9F%E8%8B%8F%E7%9C%81&page=9>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E6%B1%9F%E8%8B%8F%E7%9C%81&page=9 took longer than 30.0 seconds..
2019-10-04 12:40:08 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B1%9F%E8%8B%8F%E7%9C%81&page=10>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 120.77.45.130:80 [{'status': 500, 'reason': b'Internal Server Error'}]
2019-10-04 12:44:02 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E7%A6%8F%E5%BB%BA%E7%9C%81&page=6>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.9:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:45:41 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E7%A6%8F%E5%BB%BA%E7%9C%81&page=8>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 104.250.34.179:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:45:53 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E7%A6%8F%E5%BB%BA%E7%9C%81&page=12>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.187:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:47:27 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%99%E6%B1%9F%E7%9C%81&page=23>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%99%E6%B1%9F%E7%9C%81&page=23 took longer than 30.0 seconds..
2019-10-04 12:48:06 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E7%A6%8F%E5%BB%BA%E7%9C%81&page=20>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.190:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:48:42 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%99%E6%B1%9F%E7%9C%81&page=1>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%99%E6%B1%9F%E7%9C%81&page=1 took longer than 30.0 seconds..
