2019-10-04 10:43:13 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%9D%92%E6%B5%B7%E7%9C%81&page=18>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.135.24.11:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 10:43:26 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%9D%92%E6%B5%B7%E7%9C%81&page=1>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.8:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 10:59:54 [py.warnings] WARNING: D:\Miniconda3\lib\site-packages\pymysql\cursors.py:329: Warning: (1265, "Data truncated for column 'title' at row 1")
  self._do_get_result()

2019-10-04 11:05:30 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%8C%97%E4%BA%AC%E5%B8%82&page=2>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.194:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:13:09 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%8C%97%E4%BA%AC%E5%B8%82&page=4>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E5%8C%97%E4%BA%AC%E5%B8%82&page=4 took longer than 30.0 seconds..
2019-10-04 11:18:12 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%8C%97%E4%BA%AC%E5%B8%82&page=12>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.184:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:18:49 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%8C%97%E4%BA%AC%E5%B8%82&page=20>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.107.98:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:19:00 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%8C%97%E4%BA%AC%E5%B8%82&page=21>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 106.52.181.184:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:19:44 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%8C%97%E4%BA%AC%E5%B8%82&page=14>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 124.161.160.251:8085 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:19:55 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%8C%97%E4%BA%AC%E5%B8%82&page=30>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 120.77.45.130:80 [{'status': 500, 'reason': b'Internal Server Error'}]
2019-10-04 11:20:03 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%A4%A9%E6%B4%A5%E5%B8%82&page=3>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.194:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:20:11 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%8C%97%E4%BA%AC%E5%B8%82&page=22>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.187:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:21:35 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%8C%97%E4%BA%AC%E5%B8%82&page=29>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.TCPTimedOutError: TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2019-10-04 11:21:35 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%A4%A9%E6%B4%A5%E5%B8%82&page=7>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.TCPTimedOutError: TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2019-10-04 11:21:35 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%A4%A9%E6%B4%A5%E5%B8%82&page=9>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.224:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:21:41 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%A4%A9%E6%B4%A5%E5%B8%82&page=10>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.10:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:22:35 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%A4%A9%E6%B4%A5%E5%B8%82&page=21>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.9:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:22:42 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%A4%A9%E6%B4%A5%E5%B8%82&page=29>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2019-10-04 11:23:17 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E4%B8%8A%E6%B5%B7%E5%B8%82&page=4>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E4%B8%8A%E6%B5%B7%E5%B8%82&page=4 took longer than 30.0 seconds..
2019-10-04 11:23:28 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E4%B8%8A%E6%B5%B7%E5%B8%82&page=6>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.224:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:24:15 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E4%B8%8A%E6%B5%B7%E5%B8%82&page=12>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.9:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:24:30 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E4%B8%8A%E6%B5%B7%E5%B8%82&page=16>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 120.77.45.130:80 [{'status': 500, 'reason': b'Internal Server Error'}]
2019-10-04 11:24:46 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E4%B8%8A%E6%B5%B7%E5%B8%82&page=19>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2019-10-04 11:24:55 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E4%B8%8A%E6%B5%B7%E5%B8%82&page=24>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 120.77.45.130:80 [{'status': 500, 'reason': b'Internal Server Error'}]
2019-10-04 11:25:30 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E4%B8%8A%E6%B5%B7%E5%B8%82&page=26>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.185:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:25:59 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E4%B8%8A%E6%B5%B7%E5%B8%82&page=22>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.9:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:43:02 [py.warnings] WARNING: D:\Miniconda3\lib\site-packages\pymysql\cursors.py:329: Warning: (1265, "Data truncated for column 'title' at row 1")
  self._do_get_result()

2019-10-04 11:44:59 [py.warnings] WARNING: D:\Miniconda3\lib\site-packages\pymysql\cursors.py:329: Warning: (1265, "Data truncated for column 'title' at row 1")
  self._do_get_result()

2019-10-04 11:49:51 [py.warnings] WARNING: D:\Miniconda3\lib\site-packages\pymysql\cursors.py:329: Warning: (1265, "Data truncated for column 'title' at row 1")
  self._do_get_result()

2019-10-04 11:52:49 [py.warnings] WARNING: D:\Miniconda3\lib\site-packages\pymysql\cursors.py:329: Warning: (1265, "Data truncated for column 'title' at row 1")
  self._do_get_result()

2019-10-04 11:53:22 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%8C%97%E4%BA%AC%E5%B8%82&page=12>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.226:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:53:23 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%8C%97%E4%BA%AC%E5%B8%82&page=10>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.TCPTimedOutError: TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2019-10-04 11:57:29 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%A4%A9%E6%B4%A5%E5%B8%82&page=17>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.TCPTimedOutError: TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2019-10-04 11:57:57 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%8C%97%E4%BA%AC%E5%B8%82&page=10>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.184:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 11:58:02 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%A4%A9%E6%B4%A5%E5%B8%82&page=17>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 120.77.45.130:80 [{'status': 500, 'reason': b'Internal Server Error'}]
2019-10-04 11:58:17 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%A4%A9%E6%B4%A5%E5%B8%82&page=25>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E5%A4%A9%E6%B4%A5%E5%B8%82&page=25 took longer than 30.0 seconds..
2019-10-04 12:00:54 [py.warnings] WARNING: D:\Miniconda3\lib\site-packages\pymysql\cursors.py:329: Warning: (1265, "Data truncated for column 'title' at row 1")
  self._do_get_result()

2019-10-04 12:01:57 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E4%B8%8A%E6%B5%B7%E5%B8%82&page=22>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.226:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:03:44 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E4%B8%8A%E6%B5%B7%E5%B8%82&page=22>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 27.159.166.62:9999 [{'status': 503, 'reason': b'Service Unavailable'}]
2019-10-04 12:04:13 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%87%8D%E5%BA%86%E5%B8%82&page=23>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.8:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:06:32 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%87%8D%E5%BA%86%E5%B8%82&page=23>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.186:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:07:24 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B2%B3%E5%8C%97%E7%9C%81&page=16>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.225:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:08:20 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%A4%A9%E6%B4%A5%E5%B8%82&page=17>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.221:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:10:18 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%87%8D%E5%BA%86%E5%B8%82&page=23>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E9%87%8D%E5%BA%86%E5%B8%82&page=23 took longer than 30.0 seconds..
2019-10-04 12:11:01 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B2%B3%E5%8C%97%E7%9C%81&page=28>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.222:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:11:25 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B2%B3%E5%8C%97%E7%9C%81&page=8>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.TCPTimedOutError: TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2019-10-04 12:13:10 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B1%B1%E8%A5%BF%E7%9C%81&page=22>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.190:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:13:49 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B1%B1%E8%A5%BF%E7%9C%81&page=29>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.10:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:13:50 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E8%BE%BD%E5%AE%81%E7%9C%81&page=1>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E8%BE%BD%E5%AE%81%E7%9C%81&page=1 took longer than 30.0 seconds..
2019-10-04 12:14:36 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E8%BE%BD%E5%AE%81%E7%9C%81&page=7>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.9:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:17:38 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B2%B3%E5%8C%97%E7%9C%81&page=28>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 124.161.160.251:8085 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:20:02 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B1%B1%E8%A5%BF%E7%9C%81&page=22>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 117.191.11.107:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:21:43 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B1%B1%E8%A5%BF%E7%9C%81&page=29>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.223:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:24:51 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B1%B1%E8%A5%BF%E7%9C%81&page=22>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.189:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:25:03 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%BB%91%E9%BE%99%E6%B1%9F%E7%9C%81&page=13>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.184:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:25:35 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%BB%91%E9%BE%99%E6%B1%9F%E7%9C%81&page=22>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.223:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:25:38 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B1%B1%E8%A5%BF%E7%9C%81&page=22>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.8:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:26:02 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%BB%91%E9%BE%99%E6%B1%9F%E7%9C%81&page=29>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.195:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:26:24 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%BB%91%E9%BE%99%E6%B1%9F%E7%9C%81&page=16>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E9%BB%91%E9%BE%99%E6%B1%9F%E7%9C%81&page=16 took longer than 30.0 seconds..
2019-10-04 12:26:31 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%BB%91%E9%BE%99%E6%B1%9F%E7%9C%81&page=30>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E9%BB%91%E9%BE%99%E6%B1%9F%E7%9C%81&page=30 took longer than 30.0 seconds..
2019-10-04 12:31:13 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B1%9F%E8%8B%8F%E7%9C%81&page=23>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.221:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:33:19 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%99%E6%B1%9F%E7%9C%81&page=1>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%99%E6%B1%9F%E7%9C%81&page=1 took longer than 30.0 seconds..
2019-10-04 12:35:46 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%99%E6%B1%9F%E7%9C%81&page=23>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%99%E6%B1%9F%E7%9C%81&page=23 took longer than 30.0 seconds..
2019-10-04 12:36:33 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B1%9F%E8%8B%8F%E7%9C%81&page=8>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.184:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:37:13 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B1%9F%E8%8B%8F%E7%9C%81&page=9>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.10:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:38:20 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B1%9F%E8%8B%8F%E7%9C%81&page=10>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E6%B1%9F%E8%8B%8F%E7%9C%81&page=10 took longer than 30.0 seconds..
2019-10-04 12:39:41 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%BB%91%E9%BE%99%E6%B1%9F%E7%9C%81&page=30>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E9%BB%91%E9%BE%99%E6%B1%9F%E7%9C%81&page=30 took longer than 30.0 seconds..
2019-10-04 12:39:55 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B1%9F%E8%8B%8F%E7%9C%81&page=9>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E6%B1%9F%E8%8B%8F%E7%9C%81&page=9 took longer than 30.0 seconds..
2019-10-04 12:40:08 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B1%9F%E8%8B%8F%E7%9C%81&page=10>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 120.77.45.130:80 [{'status': 500, 'reason': b'Internal Server Error'}]
2019-10-04 12:44:02 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E7%A6%8F%E5%BB%BA%E7%9C%81&page=6>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.9:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:45:41 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E7%A6%8F%E5%BB%BA%E7%9C%81&page=8>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 104.250.34.179:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:45:53 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E7%A6%8F%E5%BB%BA%E7%9C%81&page=12>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.187:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:47:27 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%99%E6%B1%9F%E7%9C%81&page=23>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%99%E6%B1%9F%E7%9C%81&page=23 took longer than 30.0 seconds..
2019-10-04 12:48:06 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E7%A6%8F%E5%BB%BA%E7%9C%81&page=20>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.190:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:48:42 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%99%E6%B1%9F%E7%9C%81&page=1>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%99%E6%B1%9F%E7%9C%81&page=1 took longer than 30.0 seconds..
2019-10-04 12:51:46 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%99%E6%B1%9F%E7%9C%81&page=23>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%99%E6%B1%9F%E7%9C%81&page=23 took longer than 30.0 seconds..
2019-10-04 12:54:54 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E7%A6%8F%E5%BB%BA%E7%9C%81&page=8>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 106.52.181.184:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:55:36 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B1%9F%E8%A5%BF%E7%9C%81&page=14>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.220:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:56:42 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%99%E6%B1%9F%E7%9C%81&page=6>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.195:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:57:54 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B1%9F%E8%A5%BF%E7%9C%81&page=24>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.222:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:57:59 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%99%E6%B1%9F%E7%9C%81&page=23>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.187:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:58:02 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%99%E6%B1%9F%E7%9C%81&page=15>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.189:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:58:11 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B1%B1%E4%B8%9C%E7%9C%81&page=4>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 124.161.160.251:8085 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:58:35 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B1%B1%E4%B8%9C%E7%9C%81&page=3>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E5%B1%B1%E4%B8%9C%E7%9C%81&page=3 took longer than 30.0 seconds..
2019-10-04 12:58:39 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%99%E6%B1%9F%E7%9C%81&page=21>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.10:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:59:10 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B1%B1%E4%B8%9C%E7%9C%81&page=9>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 104.250.34.179:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 12:59:33 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B1%B1%E4%B8%9C%E7%9C%81&page=13>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.185:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:00:36 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B1%B1%E4%B8%9C%E7%9C%81&page=23>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.184:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:00:49 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B1%B1%E4%B8%9C%E7%9C%81&page=26>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.191:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:02:38 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B2%B3%E5%8D%97%E7%9C%81&page=9>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.190:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:03:03 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B1%B1%E4%B8%9C%E7%9C%81&page=9>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E5%B1%B1%E4%B8%9C%E7%9C%81&page=9 took longer than 30.0 seconds..
2019-10-04 13:03:41 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B1%B1%E4%B8%9C%E7%9C%81&page=13>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.190:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:04:06 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B2%B3%E5%8D%97%E7%9C%81&page=18>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.193:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:04:38 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B2%B3%E5%8D%97%E7%9C%81&page=21>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.10:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:05:25 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B2%B3%E5%8D%97%E7%9C%81&page=24>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E6%B2%B3%E5%8D%97%E7%9C%81&page=24 took longer than 30.0 seconds..
2019-10-04 13:06:17 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B2%B3%E5%8D%97%E7%9C%81&page=12>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.220:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:07:09 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B9%96%E5%8C%97%E7%9C%81&page=3>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.TCPTimedOutError: TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2019-10-04 13:10:42 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B9%96%E5%8C%97%E7%9C%81&page=5>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.226:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:12:17 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E7%A6%8F%E5%BB%BA%E7%9C%81&page=8>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.226:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:16:53 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B9%96%E5%8C%97%E7%9C%81&page=5>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.8:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:21:33 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B9%96%E5%8C%97%E7%9C%81&page=29>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 120.77.45.130:80 [{'status': 500, 'reason': b'Internal Server Error'}]
2019-10-04 13:21:40 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B9%96%E5%8D%97%E7%9C%81&page=25>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 119.41.236.180:8010 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:22:01 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B9%96%E5%8C%97%E7%9C%81&page=30>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.8:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:22:26 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B9%96%E5%8D%97%E7%9C%81&page=26>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 120.77.45.130:80 [{'status': 500, 'reason': b'Internal Server Error'}]
2019-10-04 13:22:31 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B9%96%E5%8D%97%E7%9C%81&page=1>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.188:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:24:05 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B9%BF%E4%B8%9C%E7%9C%81&page=3>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 124.161.160.251:8085 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:27:41 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B9%BF%E4%B8%9C%E7%9C%81&page=18>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.190:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:28:30 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B9%BF%E4%B8%9C%E7%9C%81&page=18>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E5%B9%BF%E4%B8%9C%E7%9C%81&page=18 took longer than 30.0 seconds..
2019-10-04 13:28:39 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B9%BF%E4%B8%9C%E7%9C%81&page=25>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.8:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:28:40 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B9%BF%E4%B8%9C%E7%9C%81&page=19>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E5%B9%BF%E4%B8%9C%E7%9C%81&page=19 took longer than 30.0 seconds..
2019-10-04 13:28:44 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B9%BF%E4%B8%9C%E7%9C%81&page=19>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.192:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:30:25 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B9%BF%E4%B8%9C%E7%9C%81&page=26>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.10:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:31:26 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%B7%E5%8D%97%E7%9C%81&page=5>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 192.117.146.110:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:32:23 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%B7%E5%8D%97%E7%9C%81&page=8>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%B7%E5%8D%97%E7%9C%81&page=8 took longer than 30.0 seconds..
2019-10-04 13:32:24 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%B7%E5%8D%97%E7%9C%81&page=15>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 106.52.181.184:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:33:39 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B9%BF%E4%B8%9C%E7%9C%81&page=14>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.189:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:34:09 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B9%BF%E4%B8%9C%E7%9C%81&page=18>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.223:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:34:35 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B9%BF%E4%B8%9C%E7%9C%81&page=19>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.222:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:34:56 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B9%BF%E4%B8%9C%E7%9C%81&page=25>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.189:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:35:14 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%B7%E5%8D%97%E7%9C%81&page=6>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.135.24.11:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:35:37 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%B7%E5%8D%97%E7%9C%81&page=8>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.8:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:36:01 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%B7%E5%8D%97%E7%9C%81&page=15>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.187:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:36:27 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%B7%E5%8D%97%E7%9C%81&page=5>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 106.52.181.184:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:36:41 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%B7%E5%8D%97%E7%9C%81&page=8>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 120.77.45.130:80 [{'status': 500, 'reason': b'Internal Server Error'}]
2019-10-04 13:37:05 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%B7%E5%8D%97%E7%9C%81&page=6>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%B7%E5%8D%97%E7%9C%81&page=6 took longer than 30.0 seconds..
2019-10-04 13:37:50 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%B7%E5%8D%97%E7%9C%81&page=21>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.222:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:38:05 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%B7%E5%8D%97%E7%9C%81&page=15>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E6%B5%B7%E5%8D%97%E7%9C%81&page=15 took longer than 30.0 seconds..
2019-10-04 13:38:09 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%9B%9B%E5%B7%9D%E7%9C%81&page=4>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.223:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:38:49 [py.warnings] WARNING: D:\Miniconda3\lib\site-packages\pymysql\cursors.py:329: Warning: (1265, "Data truncated for column 'title' at row 1")
  self._do_get_result()

2019-10-04 13:39:41 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%9B%9B%E5%B7%9D%E7%9C%81&page=7>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E5%9B%9B%E5%B7%9D%E7%9C%81&page=7 took longer than 30.0 seconds..
2019-10-04 13:40:27 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%9B%9B%E5%B7%9D%E7%9C%81&page=11>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.194:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:42:54 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%9B%9B%E5%B7%9D%E7%9C%81&page=11>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E5%9B%9B%E5%B7%9D%E7%9C%81&page=11 took longer than 30.0 seconds..
2019-10-04 13:44:06 [py.warnings] WARNING: D:\Miniconda3\lib\site-packages\pymysql\cursors.py:329: Warning: (1265, "Data truncated for column 'title' at row 1")
  self._do_get_result()

2019-10-04 13:49:38 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E8%B4%B5%E5%B7%9E%E7%9C%81&page=8>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.195:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:50:36 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E8%B4%B5%E5%B7%9E%E7%9C%81&page=24>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.225:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:50:37 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E8%B4%B5%E5%B7%9E%E7%9C%81&page=24>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2019-10-04 13:50:39 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E8%B4%B5%E5%B7%9E%E7%9C%81&page=20>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E8%B4%B5%E5%B7%9E%E7%9C%81&page=20 took longer than 30.0 seconds..
2019-10-04 13:52:44 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E4%BA%91%E5%8D%97%E7%9C%81&page=5>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E4%BA%91%E5%8D%97%E7%9C%81&page=5 took longer than 30.0 seconds..
2019-10-04 13:53:36 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E4%BA%91%E5%8D%97%E7%9C%81&page=16>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 124.161.160.251:8085 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:53:38 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E4%BA%91%E5%8D%97%E7%9C%81&page=5>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E4%BA%91%E5%8D%97%E7%9C%81&page=5 took longer than 30.0 seconds..
2019-10-04 13:53:58 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E4%BA%91%E5%8D%97%E7%9C%81&page=7>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.194:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:54:10 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E4%BA%91%E5%8D%97%E7%9C%81&page=20>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E4%BA%91%E5%8D%97%E7%9C%81&page=20 took longer than 30.0 seconds..
2019-10-04 13:55:50 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E4%BA%91%E5%8D%97%E7%9C%81&page=11>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E4%BA%91%E5%8D%97%E7%9C%81&page=11 took longer than 30.0 seconds..
2019-10-04 13:56:29 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E4%BA%91%E5%8D%97%E7%9C%81&page=17>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.TCPTimedOutError: TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2019-10-04 13:56:43 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E4%BA%91%E5%8D%97%E7%9C%81&page=16>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.186:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:57:59 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%99%95%E8%A5%BF%E7%9C%81&page=3>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E9%99%95%E8%A5%BF%E7%9C%81&page=3 took longer than 30.0 seconds..
2019-10-04 13:58:26 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%99%95%E8%A5%BF%E7%9C%81&page=7>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.226:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 13:59:13 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%99%95%E8%A5%BF%E7%9C%81&page=10>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.225:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:00:03 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%99%95%E8%A5%BF%E7%9C%81&page=7>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.191:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:00:24 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%99%95%E8%A5%BF%E7%9C%81&page=21>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.TCPTimedOutError: TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2019-10-04 14:00:30 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E7%94%98%E8%82%83%E7%9C%81&page=1>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.225:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:01:09 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%99%95%E8%A5%BF%E7%9C%81&page=20>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E9%99%95%E8%A5%BF%E7%9C%81&page=20 took longer than 30.0 seconds..
2019-10-04 14:01:12 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%99%95%E8%A5%BF%E7%9C%81&page=29>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.192:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:02:02 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%99%95%E8%A5%BF%E7%9C%81&page=29>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.225:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:02:21 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%99%95%E8%A5%BF%E7%9C%81&page=21>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.189:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:03:11 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E7%94%98%E8%82%83%E7%9C%81&page=18>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 104.250.34.179:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:03:18 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E7%94%98%E8%82%83%E7%9C%81&page=11>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.8:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:03:27 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%99%95%E8%A5%BF%E7%9C%81&page=7>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.186:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:04:03 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%99%95%E8%A5%BF%E7%9C%81&page=29>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.221:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:04:22 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E4%BA%91%E5%8D%97%E7%9C%81&page=11>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.226:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:04:22 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%99%95%E8%A5%BF%E7%9C%81&page=20>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 117.191.11.107:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:04:54 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E7%94%98%E8%82%83%E7%9C%81&page=25>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.194:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:05:25 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E7%94%98%E8%82%83%E7%9C%81&page=18>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 106.52.181.184:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:05:30 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E7%94%98%E8%82%83%E7%9C%81&page=27>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.195:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:07:36 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%9D%92%E6%B5%B7%E7%9C%81&page=11>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.195:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:09:26 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%9D%92%E6%B5%B7%E7%9C%81&page=16>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.188:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:09:59 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%9D%92%E6%B5%B7%E7%9C%81&page=11>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.224:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:11:19 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%9D%92%E6%B5%B7%E7%9C%81&page=13>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.191:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:16:07 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%9D%92%E6%B5%B7%E7%9C%81&page=11>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2019-10-04 14:16:49 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%9D%92%E6%B5%B7%E7%9C%81&page=16>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.193:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:17:27 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%8F%B0%E6%B9%BE%E7%9C%81&page=9>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.195:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:18:07 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%99%95%E8%A5%BF%E7%9C%81&page=7>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.190:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:18:29 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%99%95%E8%A5%BF%E7%9C%81&page=29>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.135.24.11:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:19:10 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%9D%92%E6%B5%B7%E7%9C%81&page=28>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.TCPTimedOutError: TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2019-10-04 14:21:05 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%8F%B0%E6%B9%BE%E7%9C%81&page=9>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.TCPTimedOutError: TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2019-10-04 14:23:30 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%86%85%E8%92%99%E5%8F%A4%E8%87%AA%E6%B2%BB%E5%8C%BA&page=2>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E5%86%85%E8%92%99%E5%8F%A4%E8%87%AA%E6%B2%BB%E5%8C%BA&page=2 took longer than 30.0 seconds..
2019-10-04 14:23:34 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%86%85%E8%92%99%E5%8F%A4%E8%87%AA%E6%B2%BB%E5%8C%BA&page=7>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.9:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:23:37 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%9D%92%E6%B5%B7%E7%9C%81&page=16>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.220:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:24:17 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%86%85%E8%92%99%E5%8F%A4%E8%87%AA%E6%B2%BB%E5%8C%BA&page=9>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.135.24.11:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:24:20 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%86%85%E8%92%99%E5%8F%A4%E8%87%AA%E6%B2%BB%E5%8C%BA&page=9>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E5%86%85%E8%92%99%E5%8F%A4%E8%87%AA%E6%B2%BB%E5%8C%BA&page=9 took longer than 30.0 seconds..
2019-10-04 14:24:35 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%86%85%E8%92%99%E5%8F%A4%E8%87%AA%E6%B2%BB%E5%8C%BA&page=2>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.221:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:28:29 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%86%85%E8%92%99%E5%8F%A4%E8%87%AA%E6%B2%BB%E5%8C%BA&page=25>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.191:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:28:51 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%86%85%E8%92%99%E5%8F%A4%E8%87%AA%E6%B2%BB%E5%8C%BA&page=25>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E5%86%85%E8%92%99%E5%8F%A4%E8%87%AA%E6%B2%BB%E5%8C%BA&page=25 took longer than 30.0 seconds..
2019-10-04 14:29:05 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%9D%92%E6%B5%B7%E7%9C%81&page=28>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 104.250.34.179:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:29:23 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%8F%B0%E6%B9%BE%E7%9C%81&page=9>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.220:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:29:47 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B9%BF%E8%A5%BF%E5%A3%AE%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=12>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 106.52.181.184:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:29:47 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B9%BF%E8%A5%BF%E5%A3%AE%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=2>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E5%B9%BF%E8%A5%BF%E5%A3%AE%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=2 took longer than 30.0 seconds..
2019-10-04 14:29:47 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B9%BF%E8%A5%BF%E5%A3%AE%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=2>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E5%B9%BF%E8%A5%BF%E5%A3%AE%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=2 took longer than 30.0 seconds..
2019-10-04 14:29:50 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B9%BF%E8%A5%BF%E5%A3%AE%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=8>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.186:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:30:41 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B9%BF%E8%A5%BF%E5%A3%AE%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=12>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.185:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:31:23 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%86%85%E8%92%99%E5%8F%A4%E8%87%AA%E6%B2%BB%E5%8C%BA&page=9>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.191:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:31:32 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B9%BF%E8%A5%BF%E5%A3%AE%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=26>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 104.250.34.179:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:32:09 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B9%BF%E8%A5%BF%E5%A3%AE%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=27>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.185:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:33:19 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E8%A5%BF%E8%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=20>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.TCPTimedOutError: TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2019-10-04 14:33:22 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E8%A5%BF%E8%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=18>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 119.41.236.180:8010 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:33:46 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B9%BF%E8%A5%BF%E5%A3%AE%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=26>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E5%B9%BF%E8%A5%BF%E5%A3%AE%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=26 took longer than 30.0 seconds..
2019-10-04 14:33:46 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%86%85%E8%92%99%E5%8F%A4%E8%87%AA%E6%B2%BB%E5%8C%BA&page=25>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 195.154.207.153:80 [{'status': 500, 'reason': b'Internal Server Error'}]
2019-10-04 14:33:52 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E8%A5%BF%E8%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=15>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 117.191.11.107:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:33:55 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E8%A5%BF%E8%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=20>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.188:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:33:56 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E8%A5%BF%E8%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=15>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.194:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:33:57 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E8%A5%BF%E8%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=10>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E8%A5%BF%E8%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=10 took longer than 30.0 seconds..
2019-10-04 14:34:54 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B9%BF%E8%A5%BF%E5%A3%AE%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=12>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E5%B9%BF%E8%A5%BF%E5%A3%AE%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=12 took longer than 30.0 seconds..
2019-10-04 14:35:16 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%AE%81%E5%A4%8F%E5%9B%9E%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=14>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.220:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:35:57 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%AE%81%E5%A4%8F%E5%9B%9E%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=16>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 192.117.146.110:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:36:17 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E8%A5%BF%E8%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=15>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 104.250.34.179:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:37:20 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%B9%BF%E8%A5%BF%E5%A3%AE%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=26>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.8:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:37:32 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%AE%81%E5%A4%8F%E5%9B%9E%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=8>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.TCPTimedOutError: TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2019-10-04 14:38:05 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%AE%81%E5%A4%8F%E5%9B%9E%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=16>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.188:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:38:22 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%AE%81%E5%A4%8F%E5%9B%9E%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=21>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.185:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:38:42 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%96%B0%E7%96%86%E7%BB%B4%E5%90%BE%E5%B0%94%E8%87%AA%E6%B2%BB%E5%8C%BA&page=19>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 119.41.236.180:8010 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:38:59 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%96%B0%E7%96%86%E7%BB%B4%E5%90%BE%E5%B0%94%E8%87%AA%E6%B2%BB%E5%8C%BA&page=28>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.190:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:39:03 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%A6%99%E6%B8%AF%E7%89%B9%E5%88%AB%E8%A1%8C%E6%94%BF%E5%8C%BA&page=15>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.226:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:39:06 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%BE%B3%E9%97%A8%E7%89%B9%E5%88%AB%E8%A1%8C%E6%94%BF%E5%8C%BA&page=5>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.192:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:39:08 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%BE%B3%E9%97%A8%E7%89%B9%E5%88%AB%E8%A1%8C%E6%94%BF%E5%8C%BA&page=11>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.>]
2019-10-04 14:39:11 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%96%B0%E7%96%86%E7%BB%B4%E5%90%BE%E5%B0%94%E8%87%AA%E6%B2%BB%E5%8C%BA&page=16>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.220:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:39:17 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%BE%B3%E9%97%A8%E7%89%B9%E5%88%AB%E8%A1%8C%E6%94%BF%E5%8C%BA&page=21>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2019-10-04 14:39:18 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%BE%B3%E9%97%A8%E7%89%B9%E5%88%AB%E8%A1%8C%E6%94%BF%E5%8C%BA&page=13>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2019-10-04 14:39:21 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%BE%B3%E9%97%A8%E7%89%B9%E5%88%AB%E8%A1%8C%E6%94%BF%E5%8C%BA&page=14>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.192:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:39:25 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E8%A5%BF%E8%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=15>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.107.98:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:39:34 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%AE%81%E5%A4%8F%E5%9B%9E%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=16>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E5%AE%81%E5%A4%8F%E5%9B%9E%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=16 took longer than 30.0 seconds..
2019-10-04 14:39:56 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%BE%B3%E9%97%A8%E7%89%B9%E5%88%AB%E8%A1%8C%E6%94%BF%E5%8C%BA&page=27>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E6%BE%B3%E9%97%A8%E7%89%B9%E5%88%AB%E8%A1%8C%E6%94%BF%E5%8C%BA&page=27 took longer than 30.0 seconds..
2019-10-04 14:40:12 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E5%AE%81%E5%A4%8F%E5%9B%9E%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA&page=21>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.190:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:40:24 [py.warnings] WARNING: D:\Miniconda3\lib\site-packages\pymysql\cursors.py:329: Warning: (1265, "Data truncated for column 'title' at row 1")
  self._do_get_result()

2019-10-04 14:40:27 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%96%B0%E7%96%86%E7%BB%B4%E5%90%BE%E5%B0%94%E8%87%AA%E6%B2%BB%E5%8C%BA&page=16>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.189:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:40:32 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%A6%99%E6%B8%AF%E7%89%B9%E5%88%AB%E8%A1%8C%E6%94%BF%E5%8C%BA&page=15>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.69.10:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:40:59 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%96%B0%E7%96%86%E7%BB%B4%E5%90%BE%E5%B0%94%E8%87%AA%E6%B2%BB%E5%8C%BA&page=19>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E6%96%B0%E7%96%86%E7%BB%B4%E5%90%BE%E5%B0%94%E8%87%AA%E6%B2%BB%E5%8C%BA&page=19 took longer than 30.0 seconds..
2019-10-04 14:41:00 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%A6%99%E6%B8%AF%E7%89%B9%E5%88%AB%E8%A1%8C%E6%94%BF%E5%8C%BA&page=3>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 39.137.107.98:80 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:41:03 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%BE%B3%E9%97%A8%E7%89%B9%E5%88%AB%E8%A1%8C%E6%94%BF%E5%8C%BA&page=21>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E6%BE%B3%E9%97%A8%E7%89%B9%E5%88%AB%E8%A1%8C%E6%94%BF%E5%8C%BA&page=21 took longer than 30.0 seconds..
2019-10-04 14:41:07 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%BE%B3%E9%97%A8%E7%89%B9%E5%88%AB%E8%A1%8C%E6%94%BF%E5%8C%BA&page=27>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E6%BE%B3%E9%97%A8%E7%89%B9%E5%88%AB%E8%A1%8C%E6%94%BF%E5%8C%BA&page=27 took longer than 30.0 seconds..
2019-10-04 14:41:20 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%96%B0%E7%96%86%E7%BB%B4%E5%90%BE%E5%B0%94%E8%87%AA%E6%B2%BB%E5%8C%BA&page=16>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.TCPTimedOutError: TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2019-10-04 14:41:24 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%BE%B3%E9%97%A8%E7%89%B9%E5%88%AB%E8%A1%8C%E6%94%BF%E5%8C%BA&page=21>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.TCPTimedOutError: TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2019-10-04 14:41:29 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%96%B0%E7%96%86%E7%BB%B4%E5%90%BE%E5%B0%94%E8%87%AA%E6%B2%BB%E5%8C%BA&page=26>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.226:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:41:31 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%96%B0%E7%96%86%E7%BB%B4%E5%90%BE%E5%B0%94%E8%87%AA%E6%B2%BB%E5%8C%BA&page=26>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E6%96%B0%E7%96%86%E7%BB%B4%E5%90%BE%E5%B0%94%E8%87%AA%E6%B2%BB%E5%8C%BA&page=26 took longer than 30.0 seconds..
2019-10-04 14:42:11 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%A6%99%E6%B8%AF%E7%89%B9%E5%88%AB%E8%A1%8C%E6%94%BF%E5%8C%BA&page=3>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 117.191.11.107:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:42:25 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%A6%99%E6%B8%AF%E7%89%B9%E5%88%AB%E8%A1%8C%E6%94%BF%E5%8C%BA&page=15>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.187:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:42:29 [py.warnings] WARNING: D:\Miniconda3\lib\site-packages\pymysql\cursors.py:329: Warning: (1265, "Data truncated for column 'title' at row 1")
  self._do_get_result()

2019-10-04 14:42:44 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E6%BE%B3%E9%97%A8%E7%89%B9%E5%88%AB%E8%A1%8C%E6%94%BF%E5%8C%BA&page=21>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 111.29.3.184:8080 [{'status': 400, 'reason': b'Bad Request'}]
2019-10-04 14:47:35 [scrapy.core.scraper] ERROR: Error downloading <GET https://piao.qunar.com/ticket/list.htm?keyword=%E9%99%95%E8%A5%BF%E7%9C%81&page=29>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "D:\Miniconda3\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "D:\Miniconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\Miniconda3\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 352, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://piao.qunar.com/ticket/list.htm?keyword=%E9%99%95%E8%A5%BF%E7%9C%81&page=29 took longer than 30.0 seconds..
